// This file has been autogenerated via
// Pekspro.PolicyScope.CodeGenerator.LogicTest.Workers.LogicGenerator

using Pekspro.PolicyScope.LogicTest.Services;
using System.Threading.Tasks;

namespace Pekspro.PolicyScope.LogicTest.Workers
{
    public class Logic : ILogic
    {
        public IPolicyScopeBuilder PolicyScopeBuilder { get; }

        public Logic(IPolicyScopeBuilder policyScopeBuilder)
        {
            PolicyScopeBuilder = policyScopeBuilder;
        }

        public int LatestResult { get; set; }

        public Task RunWithNoResultNoServiceAsync()
        {
            LatestResult = -1;

            return PolicyScopeBuilder
                .WithAsyncPolicy(PolicyNames.AsyncPolicyName)
                .WithNoService()
                .WithNoResult()
                .RunAsync(() =>
                {
                    LatestResult = 0;

                    return Task.CompletedTask;
                });
        }

        public Task RunWithNoResult1ServiceAsync()
        {
            LatestResult = -1;

            return PolicyScopeBuilder
                .WithAsyncPolicy(PolicyNames.AsyncPolicyName)
                .WithService<IDummyService1>()
                .WithNoResult()
                .RunAsync(async (service1) =>
                {
                    LatestResult = 0;
                    LatestResult += await service1.CalculateAsync();
                });
        }

        public Task RunWithNoResult2ServiceAsync()
        {
            LatestResult = -1;

            return PolicyScopeBuilder
                .WithAsyncPolicy(PolicyNames.AsyncPolicyName)
                .WithServices<IDummyService1, IDummyService2>()
                .WithNoResult()
                .RunAsync(async (service1, service2) =>
                {
                    LatestResult = 0;
                    LatestResult += await service1.CalculateAsync();
                    LatestResult += await service2.CalculateAsync();
                });
        }

        public Task RunWithNoResult3ServiceAsync()
        {
            LatestResult = -1;

            return PolicyScopeBuilder
                .WithAsyncPolicy(PolicyNames.AsyncPolicyName)
                .WithServices<IDummyService1, IDummyService2, IDummyService3>()
                .WithNoResult()
                .RunAsync(async (service1, service2, service3) =>
                {
                    LatestResult = 0;
                    LatestResult += await service1.CalculateAsync();
                    LatestResult += await service2.CalculateAsync();
                    LatestResult += await service3.CalculateAsync();
                });
        }

        public Task RunWithNoResult4ServiceAsync()
        {
            LatestResult = -1;

            return PolicyScopeBuilder
                .WithAsyncPolicy(PolicyNames.AsyncPolicyName)
                .WithServices<IDummyService1, IDummyService2, IDummyService3, IDummyService4>()
                .WithNoResult()
                .RunAsync(async (service1, service2, service3, service4) =>
                {
                    LatestResult = 0;
                    LatestResult += await service1.CalculateAsync();
                    LatestResult += await service2.CalculateAsync();
                    LatestResult += await service3.CalculateAsync();
                    LatestResult += await service4.CalculateAsync();
                });
        }

        public Task<int> RunWithResultNoServiceAsync()
        {
            LatestResult = -1;

            return PolicyScopeBuilder
                .WithAsyncPolicy(PolicyNames.AsyncPolicyName)
                .WithNoService()
                .WithResult<int>()
                .RunAsync(() =>
                {
                    LatestResult = 0;

                    return Task.FromResult(LatestResult);
                });
        }

        public Task<int> RunWithResult1ServiceAsync()
        {
            LatestResult = -1;

            return PolicyScopeBuilder
                .WithAsyncPolicy(PolicyNames.AsyncPolicyName)
                .WithService<IDummyService1>()
                .WithResult<int>()
                .RunAsync(async (service1) =>
                {
                    LatestResult = 0;
                    LatestResult += await service1.CalculateAsync();

                    return LatestResult;
                });
        }

        public Task<int> RunWithResult2ServiceAsync()
        {
            LatestResult = -1;

            return PolicyScopeBuilder
                .WithAsyncPolicy(PolicyNames.AsyncPolicyName)
                .WithServices<IDummyService1, IDummyService2>()
                .WithResult<int>()
                .RunAsync(async (service1, service2) =>
                {
                    LatestResult = 0;
                    LatestResult += await service1.CalculateAsync();
                    LatestResult += await service2.CalculateAsync();

                    return LatestResult;
                });
        }

        public Task<int> RunWithResult3ServiceAsync()
        {
            LatestResult = -1;

            return PolicyScopeBuilder
                .WithAsyncPolicy(PolicyNames.AsyncPolicyName)
                .WithServices<IDummyService1, IDummyService2, IDummyService3>()
                .WithResult<int>()
                .RunAsync(async (service1, service2, service3) =>
                {
                    LatestResult = 0;
                    LatestResult += await service1.CalculateAsync();
                    LatestResult += await service2.CalculateAsync();
                    LatestResult += await service3.CalculateAsync();

                    return LatestResult;
                });
        }

        public Task<int> RunWithResult4ServiceAsync()
        {
            LatestResult = -1;

            return PolicyScopeBuilder
                .WithAsyncPolicy(PolicyNames.AsyncPolicyName)
                .WithServices<IDummyService1, IDummyService2, IDummyService3, IDummyService4>()
                .WithResult<int>()
                .RunAsync(async (service1, service2, service3, service4) =>
                {
                    LatestResult = 0;
                    LatestResult += await service1.CalculateAsync();
                    LatestResult += await service2.CalculateAsync();
                    LatestResult += await service3.CalculateAsync();
                    LatestResult += await service4.CalculateAsync();

                    return LatestResult;
                });
        }

        public void RunWithNoResultNoService()
        {
            LatestResult = -1;

            PolicyScopeBuilder
                .WithSyncPolicy(PolicyNames.SyncPolicyName)
                .WithNoService()
                .WithNoResult()
                .Run(() =>
                {
                    LatestResult = 0;
                });
        }

        public void RunWithNoResult1Service()
        {
            LatestResult = -1;

            PolicyScopeBuilder
                .WithSyncPolicy(PolicyNames.SyncPolicyName)
                .WithService<IDummyService1>()
                .WithNoResult()
                .Run((service1) =>
                {
                    LatestResult = 0;
                    LatestResult += service1.Calculate();
                });
        }

        public void RunWithNoResult2Service()
        {
            LatestResult = -1;

            PolicyScopeBuilder
                .WithSyncPolicy(PolicyNames.SyncPolicyName)
                .WithServices<IDummyService1, IDummyService2>()
                .WithNoResult()
                .Run((service1, service2) =>
                {
                    LatestResult = 0;
                    LatestResult += service1.Calculate();
                    LatestResult += service2.Calculate();
                });
        }

        public void RunWithNoResult3Service()
        {
            LatestResult = -1;

            PolicyScopeBuilder
                .WithSyncPolicy(PolicyNames.SyncPolicyName)
                .WithServices<IDummyService1, IDummyService2, IDummyService3>()
                .WithNoResult()
                .Run((service1, service2, service3) =>
                {
                    LatestResult = 0;
                    LatestResult += service1.Calculate();
                    LatestResult += service2.Calculate();
                    LatestResult += service3.Calculate();
                });
        }

        public void RunWithNoResult4Service()
        {
            LatestResult = -1;

            PolicyScopeBuilder
                .WithSyncPolicy(PolicyNames.SyncPolicyName)
                .WithServices<IDummyService1, IDummyService2, IDummyService3, IDummyService4>()
                .WithNoResult()
                .Run((service1, service2, service3, service4) =>
                {
                    LatestResult = 0;
                    LatestResult += service1.Calculate();
                    LatestResult += service2.Calculate();
                    LatestResult += service3.Calculate();
                    LatestResult += service4.Calculate();
                });
        }

        public int RunWithResultNoService()
        {
            LatestResult = -1;

            return PolicyScopeBuilder
                .WithSyncPolicy(PolicyNames.SyncPolicyName)
                .WithNoService()
                .WithResult<int>()
                .Run(() =>
                {
                    LatestResult = 0;

                    return LatestResult;
                });
        }

        public int RunWithResult1Service()
        {
            LatestResult = -1;

            return PolicyScopeBuilder
                .WithSyncPolicy(PolicyNames.SyncPolicyName)
                .WithService<IDummyService1>()
                .WithResult<int>()
                .Run((service1) =>
                {
                    LatestResult = 0;
                    LatestResult += service1.Calculate();

                    return LatestResult;
                });
        }

        public int RunWithResult2Service()
        {
            LatestResult = -1;

            return PolicyScopeBuilder
                .WithSyncPolicy(PolicyNames.SyncPolicyName)
                .WithServices<IDummyService1, IDummyService2>()
                .WithResult<int>()
                .Run((service1, service2) =>
                {
                    LatestResult = 0;
                    LatestResult += service1.Calculate();
                    LatestResult += service2.Calculate();

                    return LatestResult;
                });
        }

        public int RunWithResult3Service()
        {
            LatestResult = -1;

            return PolicyScopeBuilder
                .WithSyncPolicy(PolicyNames.SyncPolicyName)
                .WithServices<IDummyService1, IDummyService2, IDummyService3>()
                .WithResult<int>()
                .Run((service1, service2, service3) =>
                {
                    LatestResult = 0;
                    LatestResult += service1.Calculate();
                    LatestResult += service2.Calculate();
                    LatestResult += service3.Calculate();

                    return LatestResult;
                });
        }

        public int RunWithResult4Service()
        {
            LatestResult = -1;

            return PolicyScopeBuilder
                .WithSyncPolicy(PolicyNames.SyncPolicyName)
                .WithServices<IDummyService1, IDummyService2, IDummyService3, IDummyService4>()
                .WithResult<int>()
                .Run((service1, service2, service3, service4) =>
                {
                    LatestResult = 0;
                    LatestResult += service1.Calculate();
                    LatestResult += service2.Calculate();
                    LatestResult += service3.Calculate();
                    LatestResult += service4.Calculate();

                    return LatestResult;
                });
        }
    }
}
