// This file has been autogenerated via
// Pekspro.PolicyScope.CodeGenerator.MainLibrary.PolicyScopeServiceSelectorGenerator

namespace Pekspro.PolicyScope
{
    public interface IAsyncPolicyScopeServiceSelector
    {
        IAsyncPolicyScopeResultSelector WithNoService();

        IAsyncPolicyScopeResultSelector<T> WithService<T>();

        IAsyncPolicyScopeResultSelector<T1, T2> WithServices<T1, T2>();

        IAsyncPolicyScopeResultSelector<T1, T2, T3> WithServices<T1, T2, T3>();

        IAsyncPolicyScopeResultSelector<T1, T2, T3, T4> WithServices<T1, T2, T3, T4>();
    }

    public interface ISyncPolicyScopeServiceSelector
    {
        ISyncPolicyScopeResultSelector WithNoService();

        ISyncPolicyScopeResultSelector<T> WithService<T>();

        ISyncPolicyScopeResultSelector<T1, T2> WithServices<T1, T2>();

        ISyncPolicyScopeResultSelector<T1, T2, T3> WithServices<T1, T2, T3>();

        ISyncPolicyScopeResultSelector<T1, T2, T3, T4> WithServices<T1, T2, T3, T4>();
    }

}
