// This file has been autogenerated via
// Pekspro.PolicyScope.CodeGenerator.MainLibrary.PolicyScopeResultSelectorGenerator

namespace Pekspro.PolicyScope
{
    public interface IAsyncPolicyScopeResultSelector
    {
        IAsyncNoServiceNoResultPolicyScopeRunner WithNoResult();

        IAsyncNoServiceResultPolicyScopeRunner<TResult> WithResult<TResult>();
    }

    public interface IAsyncPolicyScopeResultSelector<T>
    {
        IAsyncServiceNoResultPolicyScopeRunner<T> WithNoResult();

        IAsyncServiceResultPolicyScopeRunner<T, TResult> WithResult<TResult>();
    }

    public interface IAsyncPolicyScopeResultSelector<T1, T2>
    {
        IAsyncServiceNoResultPolicyScopeRunner<T1, T2> WithNoResult();

        IAsyncServiceResultPolicyScopeRunner<T1, T2, TResult> WithResult<TResult>();
    }

    public interface IAsyncPolicyScopeResultSelector<T1, T2, T3>
    {
        IAsyncServiceNoResultPolicyScopeRunner<T1, T2, T3> WithNoResult();

        IAsyncServiceResultPolicyScopeRunner<T1, T2, T3, TResult> WithResult<TResult>();
    }

    public interface IAsyncPolicyScopeResultSelector<T1, T2, T3, T4>
    {
        IAsyncServiceNoResultPolicyScopeRunner<T1, T2, T3, T4> WithNoResult();

        IAsyncServiceResultPolicyScopeRunner<T1, T2, T3, T4, TResult> WithResult<TResult>();
    }

    public interface ISyncPolicyScopeResultSelector
    {
        ISyncNoServiceNoResultPolicyScopeRunner WithNoResult();

        ISyncNoServiceResultPolicyScopeRunner<TResult> WithResult<TResult>();
    }

    public interface ISyncPolicyScopeResultSelector<T>
    {
        ISyncServiceNoResultPolicyScopeRunner<T> WithNoResult();

        ISyncServiceResultPolicyScopeRunner<T, TResult> WithResult<TResult>();
    }

    public interface ISyncPolicyScopeResultSelector<T1, T2>
    {
        ISyncServiceNoResultPolicyScopeRunner<T1, T2> WithNoResult();

        ISyncServiceResultPolicyScopeRunner<T1, T2, TResult> WithResult<TResult>();
    }

    public interface ISyncPolicyScopeResultSelector<T1, T2, T3>
    {
        ISyncServiceNoResultPolicyScopeRunner<T1, T2, T3> WithNoResult();

        ISyncServiceResultPolicyScopeRunner<T1, T2, T3, TResult> WithResult<TResult>();
    }

    public interface ISyncPolicyScopeResultSelector<T1, T2, T3, T4>
    {
        ISyncServiceNoResultPolicyScopeRunner<T1, T2, T3, T4> WithNoResult();

        ISyncServiceResultPolicyScopeRunner<T1, T2, T3, T4, TResult> WithResult<TResult>();
    }

}
