// This file has been autogenerated via
// Pekspro.PolicyScope.CodeGenerator.MainLibrary.PolicyScopeServiceSelectorGenerator

using Polly;
using System;

namespace Pekspro.PolicyScope
{
    internal class AsyncPolicyScopeServiceSelector : AsyncPolicyScopeBase, IAsyncPolicyScopeServiceSelector
    {
        internal AsyncPolicyScopeServiceSelector(IServiceProvider serviceProvider, IAsyncPolicy asyncPolicy)
            : base(serviceProvider, asyncPolicy)
        {
        }

        public IAsyncPolicyScopeResultSelector WithNoService()
        {
            return new AsyncPolicyScopeResultSelector(this);
        }

        public IAsyncPolicyScopeResultSelector<T> WithService<T>()
        {
            return new AsyncPolicyScopeResultSelector<T>(this);
        }

        public IAsyncPolicyScopeResultSelector<T1, T2> WithServices<T1, T2>()
        {
            return new AsyncPolicyScopeResultSelector<T1, T2>(this);
        }

        public IAsyncPolicyScopeResultSelector<T1, T2, T3> WithServices<T1, T2, T3>()
        {
            return new AsyncPolicyScopeResultSelector<T1, T2, T3>(this);
        }

        public IAsyncPolicyScopeResultSelector<T1, T2, T3, T4> WithServices<T1, T2, T3, T4>()
        {
            return new AsyncPolicyScopeResultSelector<T1, T2, T3, T4>(this);
        }
    }

    internal class SyncPolicyScopeServiceSelector : SyncPolicyScopeBase, ISyncPolicyScopeServiceSelector
    {
        internal SyncPolicyScopeServiceSelector(IServiceProvider serviceProvider, ISyncPolicy syncPolicy)
            : base(serviceProvider, syncPolicy)
        {
        }

        public ISyncPolicyScopeResultSelector WithNoService()
        {
            return new SyncPolicyScopeResultSelector(this);
        }

        public ISyncPolicyScopeResultSelector<T> WithService<T>()
        {
            return new SyncPolicyScopeResultSelector<T>(this);
        }

        public ISyncPolicyScopeResultSelector<T1, T2> WithServices<T1, T2>()
        {
            return new SyncPolicyScopeResultSelector<T1, T2>(this);
        }

        public ISyncPolicyScopeResultSelector<T1, T2, T3> WithServices<T1, T2, T3>()
        {
            return new SyncPolicyScopeResultSelector<T1, T2, T3>(this);
        }

        public ISyncPolicyScopeResultSelector<T1, T2, T3, T4> WithServices<T1, T2, T3, T4>()
        {
            return new SyncPolicyScopeResultSelector<T1, T2, T3, T4>(this);
        }
    }
}
