// This file has been autogenerated via
// Pekspro.PolicyScope.CodeGenerator.MainLibrary.PolicyScopeResultSelectorGenerator

namespace Pekspro.PolicyScope
{
    internal class AsyncPolicyScopeResultSelector : AsyncPolicyScopeBase, IAsyncPolicyScopeResultSelector
    {
        internal AsyncPolicyScopeResultSelector(AsyncPolicyScopeBase settings)
            : base(settings)
        {
        }

        public IAsyncNoServiceNoResultPolicyScopeRunner WithNoResult()
        {
            return new AsyncNoServiceNoResultPolicyScopeRunner(this);
        }

        public IAsyncNoServiceResultPolicyScopeRunner<TResult> WithResult<TResult>()
        {
            return new AsyncNoServiceResultPolicyScopeRunner<TResult>(this);
        }
    }

    internal class AsyncPolicyScopeResultSelector<T> : AsyncPolicyScopeBase, IAsyncPolicyScopeResultSelector<T>
    {
        internal AsyncPolicyScopeResultSelector(AsyncPolicyScopeBase settings)
            : base(settings)
        {
        }

        public IAsyncServiceNoResultPolicyScopeRunner<T> WithNoResult()
        {
            return new AsyncServiceNoResultPolicyScopeRunner<T>(this);
        }

        public IAsyncServiceResultPolicyScopeRunner<T, TResult> WithResult<TResult>()
        {
            return new AsyncServiceResultPolicyScopeRunner<T, TResult>(this);
        }
    }

    internal class AsyncPolicyScopeResultSelector<T1, T2> : AsyncPolicyScopeBase, IAsyncPolicyScopeResultSelector<T1, T2>
    {
        internal AsyncPolicyScopeResultSelector(AsyncPolicyScopeBase settings)
            : base(settings)
        {
        }

        public IAsyncServiceNoResultPolicyScopeRunner<T1, T2> WithNoResult()
        {
            return new AsyncServiceNoResultPolicyScopeRunner<T1, T2>(this);
        }

        public IAsyncServiceResultPolicyScopeRunner<T1, T2, TResult> WithResult<TResult>()
        {
            return new AsyncServiceResultPolicyScopeRunner<T1, T2, TResult>(this);
        }
    }

    internal class AsyncPolicyScopeResultSelector<T1, T2, T3> : AsyncPolicyScopeBase, IAsyncPolicyScopeResultSelector<T1, T2, T3>
    {
        internal AsyncPolicyScopeResultSelector(AsyncPolicyScopeBase settings)
            : base(settings)
        {
        }

        public IAsyncServiceNoResultPolicyScopeRunner<T1, T2, T3> WithNoResult()
        {
            return new AsyncServiceNoResultPolicyScopeRunner<T1, T2, T3>(this);
        }

        public IAsyncServiceResultPolicyScopeRunner<T1, T2, T3, TResult> WithResult<TResult>()
        {
            return new AsyncServiceResultPolicyScopeRunner<T1, T2, T3, TResult>(this);
        }
    }

    internal class AsyncPolicyScopeResultSelector<T1, T2, T3, T4> : AsyncPolicyScopeBase, IAsyncPolicyScopeResultSelector<T1, T2, T3, T4>
    {
        internal AsyncPolicyScopeResultSelector(AsyncPolicyScopeBase settings)
            : base(settings)
        {
        }

        public IAsyncServiceNoResultPolicyScopeRunner<T1, T2, T3, T4> WithNoResult()
        {
            return new AsyncServiceNoResultPolicyScopeRunner<T1, T2, T3, T4>(this);
        }

        public IAsyncServiceResultPolicyScopeRunner<T1, T2, T3, T4, TResult> WithResult<TResult>()
        {
            return new AsyncServiceResultPolicyScopeRunner<T1, T2, T3, T4, TResult>(this);
        }
    }

    internal class SyncPolicyScopeResultSelector : SyncPolicyScopeBase, ISyncPolicyScopeResultSelector
    {
        internal SyncPolicyScopeResultSelector(SyncPolicyScopeBase settings)
            : base(settings)
        {
        }

        public ISyncNoServiceNoResultPolicyScopeRunner WithNoResult()
        {
            return new SyncNoServiceNoResultPolicyScopeRunner(this);
        }

        public ISyncNoServiceResultPolicyScopeRunner<TResult> WithResult<TResult>()
        {
            return new SyncNoServiceResultPolicyScopeRunner<TResult>(this);
        }
    }

    internal class SyncPolicyScopeResultSelector<T> : SyncPolicyScopeBase, ISyncPolicyScopeResultSelector<T>
    {
        internal SyncPolicyScopeResultSelector(SyncPolicyScopeBase settings)
            : base(settings)
        {
        }

        public ISyncServiceNoResultPolicyScopeRunner<T> WithNoResult()
        {
            return new SyncServiceNoResultPolicyScopeRunner<T>(this);
        }

        public ISyncServiceResultPolicyScopeRunner<T, TResult> WithResult<TResult>()
        {
            return new SyncServiceResultPolicyScopeRunner<T, TResult>(this);
        }
    }

    internal class SyncPolicyScopeResultSelector<T1, T2> : SyncPolicyScopeBase, ISyncPolicyScopeResultSelector<T1, T2>
    {
        internal SyncPolicyScopeResultSelector(SyncPolicyScopeBase settings)
            : base(settings)
        {
        }

        public ISyncServiceNoResultPolicyScopeRunner<T1, T2> WithNoResult()
        {
            return new SyncServiceNoResultPolicyScopeRunner<T1, T2>(this);
        }

        public ISyncServiceResultPolicyScopeRunner<T1, T2, TResult> WithResult<TResult>()
        {
            return new SyncServiceResultPolicyScopeRunner<T1, T2, TResult>(this);
        }
    }

    internal class SyncPolicyScopeResultSelector<T1, T2, T3> : SyncPolicyScopeBase, ISyncPolicyScopeResultSelector<T1, T2, T3>
    {
        internal SyncPolicyScopeResultSelector(SyncPolicyScopeBase settings)
            : base(settings)
        {
        }

        public ISyncServiceNoResultPolicyScopeRunner<T1, T2, T3> WithNoResult()
        {
            return new SyncServiceNoResultPolicyScopeRunner<T1, T2, T3>(this);
        }

        public ISyncServiceResultPolicyScopeRunner<T1, T2, T3, TResult> WithResult<TResult>()
        {
            return new SyncServiceResultPolicyScopeRunner<T1, T2, T3, TResult>(this);
        }
    }

    internal class SyncPolicyScopeResultSelector<T1, T2, T3, T4> : SyncPolicyScopeBase, ISyncPolicyScopeResultSelector<T1, T2, T3, T4>
    {
        internal SyncPolicyScopeResultSelector(SyncPolicyScopeBase settings)
            : base(settings)
        {
        }

        public ISyncServiceNoResultPolicyScopeRunner<T1, T2, T3, T4> WithNoResult()
        {
            return new SyncServiceNoResultPolicyScopeRunner<T1, T2, T3, T4>(this);
        }

        public ISyncServiceResultPolicyScopeRunner<T1, T2, T3, T4, TResult> WithResult<TResult>()
        {
            return new SyncServiceResultPolicyScopeRunner<T1, T2, T3, T4, TResult>(this);
        }
    }
}
