// This file has been autogenerated via
// Pekspro.PolicyScope.CodeGenerator.Test.LogicTest.Workers.UnitTestLogicGenerator

using Moq;
using Pekspro.PolicyScope.LogicTest;
using Pekspro.PolicyScope.LogicTest.Services;
using Pekspro.PolicyScope.LogicTest.Workers;
using Pekspro.PolicyScope.Mock;
using System.Threading.Tasks;
using Xunit;

namespace Pekspro.PolicyScope.Test.LogicTest.Workers
{
    public class UnitTestLogic
    {
        [Fact]
        public async Task TestRunWithNoResultNoServiceAsync()
        {
            // Arrange
            var policyScopeMock = PolicyScopeMock
                            .AsyncPolicy(PolicyNames.AsyncPolicyName)
                            .WithNoService()
                            .WithNoResult()
                            .Build();

            Logic logic = new Logic(policyScopeMock.Object);

            // Act
            await logic.RunWithNoResultNoServiceAsync();

            // Assert
            Assert.Equal((1 << 0) - 1, logic.LatestResult);
            policyScopeMock.VerifyRunOnce();
        }

        [Fact]
        public async Task TestRunWithNoResult1ServiceAsync()
        {
            // Arrange
            Mock<IDummyService1> dummyServiceMock1 = new Mock<IDummyService1>();
            dummyServiceMock1
                .Setup(d => d.CalculateAsync())
                .Returns(Task.FromResult(1 << 0));

            var policyScopeMock = PolicyScopeMock
                            .AsyncPolicy(PolicyNames.AsyncPolicyName)
                            .WithService(dummyServiceMock1.Object)
                            .WithNoResult()
                            .Build();

            Logic logic = new Logic(policyScopeMock.Object);

            // Act
            await logic.RunWithNoResult1ServiceAsync();

            // Assert
            Assert.Equal((1 << 1) - 1, logic.LatestResult);
            policyScopeMock.VerifyRunOnce();
        }

        [Fact]
        public async Task TestRunWithNoResult2ServiceAsync()
        {
            // Arrange
            Mock<IDummyService1> dummyServiceMock1 = new Mock<IDummyService1>();
            dummyServiceMock1
                .Setup(d => d.CalculateAsync())
                .Returns(Task.FromResult(1 << 0));

            Mock<IDummyService2> dummyServiceMock2 = new Mock<IDummyService2>();
            dummyServiceMock2
                .Setup(d => d.CalculateAsync())
                .Returns(Task.FromResult(1 << 1));

            var policyScopeMock = PolicyScopeMock
                            .AsyncPolicy(PolicyNames.AsyncPolicyName)
                            .WithServices(dummyServiceMock1.Object, dummyServiceMock2.Object)
                            .WithNoResult()
                            .Build();

            Logic logic = new Logic(policyScopeMock.Object);

            // Act
            await logic.RunWithNoResult2ServiceAsync();

            // Assert
            Assert.Equal((1 << 2) - 1, logic.LatestResult);
            policyScopeMock.VerifyRunOnce();
        }

        [Fact]
        public async Task TestRunWithNoResult3ServiceAsync()
        {
            // Arrange
            Mock<IDummyService1> dummyServiceMock1 = new Mock<IDummyService1>();
            dummyServiceMock1
                .Setup(d => d.CalculateAsync())
                .Returns(Task.FromResult(1 << 0));

            Mock<IDummyService2> dummyServiceMock2 = new Mock<IDummyService2>();
            dummyServiceMock2
                .Setup(d => d.CalculateAsync())
                .Returns(Task.FromResult(1 << 1));

            Mock<IDummyService3> dummyServiceMock3 = new Mock<IDummyService3>();
            dummyServiceMock3
                .Setup(d => d.CalculateAsync())
                .Returns(Task.FromResult(1 << 2));

            var policyScopeMock = PolicyScopeMock
                            .AsyncPolicy(PolicyNames.AsyncPolicyName)
                            .WithServices(dummyServiceMock1.Object, dummyServiceMock2.Object, dummyServiceMock3.Object)
                            .WithNoResult()
                            .Build();

            Logic logic = new Logic(policyScopeMock.Object);

            // Act
            await logic.RunWithNoResult3ServiceAsync();

            // Assert
            Assert.Equal((1 << 3) - 1, logic.LatestResult);
            policyScopeMock.VerifyRunOnce();
        }

        [Fact]
        public async Task TestRunWithNoResult4ServiceAsync()
        {
            // Arrange
            Mock<IDummyService1> dummyServiceMock1 = new Mock<IDummyService1>();
            dummyServiceMock1
                .Setup(d => d.CalculateAsync())
                .Returns(Task.FromResult(1 << 0));

            Mock<IDummyService2> dummyServiceMock2 = new Mock<IDummyService2>();
            dummyServiceMock2
                .Setup(d => d.CalculateAsync())
                .Returns(Task.FromResult(1 << 1));

            Mock<IDummyService3> dummyServiceMock3 = new Mock<IDummyService3>();
            dummyServiceMock3
                .Setup(d => d.CalculateAsync())
                .Returns(Task.FromResult(1 << 2));

            Mock<IDummyService4> dummyServiceMock4 = new Mock<IDummyService4>();
            dummyServiceMock4
                .Setup(d => d.CalculateAsync())
                .Returns(Task.FromResult(1 << 3));

            var policyScopeMock = PolicyScopeMock
                            .AsyncPolicy(PolicyNames.AsyncPolicyName)
                            .WithServices(dummyServiceMock1.Object, dummyServiceMock2.Object, dummyServiceMock3.Object, dummyServiceMock4.Object)
                            .WithNoResult()
                            .Build();

            Logic logic = new Logic(policyScopeMock.Object);

            // Act
            await logic.RunWithNoResult4ServiceAsync();

            // Assert
            Assert.Equal((1 << 4) - 1, logic.LatestResult);
            policyScopeMock.VerifyRunOnce();
        }

        [Fact]
        public async Task TestRunWithResultNoServiceAsync()
        {
            // Arrange
            var policyScopeMock = PolicyScopeMock
                            .AsyncPolicy(PolicyNames.AsyncPolicyName)
                            .WithNoService()
                            .WithResultType<int>()
                            .Build();

            Logic logic = new Logic(policyScopeMock.Object);

            // Act
            int result = await logic.RunWithResultNoServiceAsync();

            // Assert
            Assert.Equal((1 << 0) - 1, result);
            Assert.Equal((1 << 0) - 1, logic.LatestResult);
            policyScopeMock.VerifyRunOnce();
        }

        [Fact]
        public async Task TestRunWithResult1ServiceAsync()
        {
            // Arrange
            Mock<IDummyService1> dummyServiceMock1 = new Mock<IDummyService1>();
            dummyServiceMock1
                .Setup(d => d.CalculateAsync())
                .Returns(Task.FromResult(1 << 0));

            var policyScopeMock = PolicyScopeMock
                            .AsyncPolicy(PolicyNames.AsyncPolicyName)
                            .WithService(dummyServiceMock1.Object)
                            .WithResultType<int>()
                            .Build();

            Logic logic = new Logic(policyScopeMock.Object);

            // Act
            int result = await logic.RunWithResult1ServiceAsync();

            // Assert
            Assert.Equal((1 << 1) - 1, result);
            Assert.Equal((1 << 1) - 1, logic.LatestResult);
            policyScopeMock.VerifyRunOnce();
        }

        [Fact]
        public async Task TestRunWithResult2ServiceAsync()
        {
            // Arrange
            Mock<IDummyService1> dummyServiceMock1 = new Mock<IDummyService1>();
            dummyServiceMock1
                .Setup(d => d.CalculateAsync())
                .Returns(Task.FromResult(1 << 0));

            Mock<IDummyService2> dummyServiceMock2 = new Mock<IDummyService2>();
            dummyServiceMock2
                .Setup(d => d.CalculateAsync())
                .Returns(Task.FromResult(1 << 1));

            var policyScopeMock = PolicyScopeMock
                            .AsyncPolicy(PolicyNames.AsyncPolicyName)
                            .WithServices(dummyServiceMock1.Object, dummyServiceMock2.Object)
                            .WithResultType<int>()
                            .Build();

            Logic logic = new Logic(policyScopeMock.Object);

            // Act
            int result = await logic.RunWithResult2ServiceAsync();

            // Assert
            Assert.Equal((1 << 2) - 1, result);
            Assert.Equal((1 << 2) - 1, logic.LatestResult);
            policyScopeMock.VerifyRunOnce();
        }

        [Fact]
        public async Task TestRunWithResult3ServiceAsync()
        {
            // Arrange
            Mock<IDummyService1> dummyServiceMock1 = new Mock<IDummyService1>();
            dummyServiceMock1
                .Setup(d => d.CalculateAsync())
                .Returns(Task.FromResult(1 << 0));

            Mock<IDummyService2> dummyServiceMock2 = new Mock<IDummyService2>();
            dummyServiceMock2
                .Setup(d => d.CalculateAsync())
                .Returns(Task.FromResult(1 << 1));

            Mock<IDummyService3> dummyServiceMock3 = new Mock<IDummyService3>();
            dummyServiceMock3
                .Setup(d => d.CalculateAsync())
                .Returns(Task.FromResult(1 << 2));

            var policyScopeMock = PolicyScopeMock
                            .AsyncPolicy(PolicyNames.AsyncPolicyName)
                            .WithServices(dummyServiceMock1.Object, dummyServiceMock2.Object, dummyServiceMock3.Object)
                            .WithResultType<int>()
                            .Build();

            Logic logic = new Logic(policyScopeMock.Object);

            // Act
            int result = await logic.RunWithResult3ServiceAsync();

            // Assert
            Assert.Equal((1 << 3) - 1, result);
            Assert.Equal((1 << 3) - 1, logic.LatestResult);
            policyScopeMock.VerifyRunOnce();
        }

        [Fact]
        public async Task TestRunWithResult4ServiceAsync()
        {
            // Arrange
            Mock<IDummyService1> dummyServiceMock1 = new Mock<IDummyService1>();
            dummyServiceMock1
                .Setup(d => d.CalculateAsync())
                .Returns(Task.FromResult(1 << 0));

            Mock<IDummyService2> dummyServiceMock2 = new Mock<IDummyService2>();
            dummyServiceMock2
                .Setup(d => d.CalculateAsync())
                .Returns(Task.FromResult(1 << 1));

            Mock<IDummyService3> dummyServiceMock3 = new Mock<IDummyService3>();
            dummyServiceMock3
                .Setup(d => d.CalculateAsync())
                .Returns(Task.FromResult(1 << 2));

            Mock<IDummyService4> dummyServiceMock4 = new Mock<IDummyService4>();
            dummyServiceMock4
                .Setup(d => d.CalculateAsync())
                .Returns(Task.FromResult(1 << 3));

            var policyScopeMock = PolicyScopeMock
                            .AsyncPolicy(PolicyNames.AsyncPolicyName)
                            .WithServices(dummyServiceMock1.Object, dummyServiceMock2.Object, dummyServiceMock3.Object, dummyServiceMock4.Object)
                            .WithResultType<int>()
                            .Build();

            Logic logic = new Logic(policyScopeMock.Object);

            // Act
            int result = await logic.RunWithResult4ServiceAsync();

            // Assert
            Assert.Equal((1 << 4) - 1, result);
            Assert.Equal((1 << 4) - 1, logic.LatestResult);
            policyScopeMock.VerifyRunOnce();
        }

        [Fact]
        public void TestRunWithNoResultNoService()
        {
            // Arrange
            var policyScopeMock = PolicyScopeMock
                            .SyncPolicy(PolicyNames.SyncPolicyName)
                            .WithNoService()
                            .WithNoResult()
                            .Build();

            Logic logic = new Logic(policyScopeMock.Object);

            // Act
            logic.RunWithNoResultNoService();

            // Assert
            Assert.Equal((1 << 0) - 1, logic.LatestResult);
            policyScopeMock.VerifyRunOnce();
        }

        [Fact]
        public void TestRunWithNoResult1Service()
        {
            // Arrange
            Mock<IDummyService1> dummyServiceMock1 = new Mock<IDummyService1>();
            dummyServiceMock1
                .Setup(d => d.Calculate())
                .Returns(1 << 0);

            var policyScopeMock = PolicyScopeMock
                            .SyncPolicy(PolicyNames.SyncPolicyName)
                            .WithService(dummyServiceMock1.Object)
                            .WithNoResult()
                            .Build();

            Logic logic = new Logic(policyScopeMock.Object);

            // Act
            logic.RunWithNoResult1Service();

            // Assert
            Assert.Equal((1 << 1) - 1, logic.LatestResult);
            policyScopeMock.VerifyRunOnce();
        }

        [Fact]
        public void TestRunWithNoResult2Service()
        {
            // Arrange
            Mock<IDummyService1> dummyServiceMock1 = new Mock<IDummyService1>();
            dummyServiceMock1
                .Setup(d => d.Calculate())
                .Returns(1 << 0);

            Mock<IDummyService2> dummyServiceMock2 = new Mock<IDummyService2>();
            dummyServiceMock2
                .Setup(d => d.Calculate())
                .Returns(1 << 1);

            var policyScopeMock = PolicyScopeMock
                            .SyncPolicy(PolicyNames.SyncPolicyName)
                            .WithServices(dummyServiceMock1.Object, dummyServiceMock2.Object)
                            .WithNoResult()
                            .Build();

            Logic logic = new Logic(policyScopeMock.Object);

            // Act
            logic.RunWithNoResult2Service();

            // Assert
            Assert.Equal((1 << 2) - 1, logic.LatestResult);
            policyScopeMock.VerifyRunOnce();
        }

        [Fact]
        public void TestRunWithNoResult3Service()
        {
            // Arrange
            Mock<IDummyService1> dummyServiceMock1 = new Mock<IDummyService1>();
            dummyServiceMock1
                .Setup(d => d.Calculate())
                .Returns(1 << 0);

            Mock<IDummyService2> dummyServiceMock2 = new Mock<IDummyService2>();
            dummyServiceMock2
                .Setup(d => d.Calculate())
                .Returns(1 << 1);

            Mock<IDummyService3> dummyServiceMock3 = new Mock<IDummyService3>();
            dummyServiceMock3
                .Setup(d => d.Calculate())
                .Returns(1 << 2);

            var policyScopeMock = PolicyScopeMock
                            .SyncPolicy(PolicyNames.SyncPolicyName)
                            .WithServices(dummyServiceMock1.Object, dummyServiceMock2.Object, dummyServiceMock3.Object)
                            .WithNoResult()
                            .Build();

            Logic logic = new Logic(policyScopeMock.Object);

            // Act
            logic.RunWithNoResult3Service();

            // Assert
            Assert.Equal((1 << 3) - 1, logic.LatestResult);
            policyScopeMock.VerifyRunOnce();
        }

        [Fact]
        public void TestRunWithNoResult4Service()
        {
            // Arrange
            Mock<IDummyService1> dummyServiceMock1 = new Mock<IDummyService1>();
            dummyServiceMock1
                .Setup(d => d.Calculate())
                .Returns(1 << 0);

            Mock<IDummyService2> dummyServiceMock2 = new Mock<IDummyService2>();
            dummyServiceMock2
                .Setup(d => d.Calculate())
                .Returns(1 << 1);

            Mock<IDummyService3> dummyServiceMock3 = new Mock<IDummyService3>();
            dummyServiceMock3
                .Setup(d => d.Calculate())
                .Returns(1 << 2);

            Mock<IDummyService4> dummyServiceMock4 = new Mock<IDummyService4>();
            dummyServiceMock4
                .Setup(d => d.Calculate())
                .Returns(1 << 3);

            var policyScopeMock = PolicyScopeMock
                            .SyncPolicy(PolicyNames.SyncPolicyName)
                            .WithServices(dummyServiceMock1.Object, dummyServiceMock2.Object, dummyServiceMock3.Object, dummyServiceMock4.Object)
                            .WithNoResult()
                            .Build();

            Logic logic = new Logic(policyScopeMock.Object);

            // Act
            logic.RunWithNoResult4Service();

            // Assert
            Assert.Equal((1 << 4) - 1, logic.LatestResult);
            policyScopeMock.VerifyRunOnce();
        }

        [Fact]
        public void TestRunWithResultNoService()
        {
            // Arrange
            var policyScopeMock = PolicyScopeMock
                            .SyncPolicy(PolicyNames.SyncPolicyName)
                            .WithNoService()
                            .WithResultType<int>()
                            .Build();

            Logic logic = new Logic(policyScopeMock.Object);

            // Act
            int result = logic.RunWithResultNoService();

            // Assert
            Assert.Equal((1 << 0) - 1, result);
            Assert.Equal((1 << 0) - 1, logic.LatestResult);
            policyScopeMock.VerifyRunOnce();
        }

        [Fact]
        public void TestRunWithResult1Service()
        {
            // Arrange
            Mock<IDummyService1> dummyServiceMock1 = new Mock<IDummyService1>();
            dummyServiceMock1
                .Setup(d => d.Calculate())
                .Returns(1 << 0);

            var policyScopeMock = PolicyScopeMock
                            .SyncPolicy(PolicyNames.SyncPolicyName)
                            .WithService(dummyServiceMock1.Object)
                            .WithResultType<int>()
                            .Build();

            Logic logic = new Logic(policyScopeMock.Object);

            // Act
            int result = logic.RunWithResult1Service();

            // Assert
            Assert.Equal((1 << 1) - 1, result);
            Assert.Equal((1 << 1) - 1, logic.LatestResult);
            policyScopeMock.VerifyRunOnce();
        }

        [Fact]
        public void TestRunWithResult2Service()
        {
            // Arrange
            Mock<IDummyService1> dummyServiceMock1 = new Mock<IDummyService1>();
            dummyServiceMock1
                .Setup(d => d.Calculate())
                .Returns(1 << 0);

            Mock<IDummyService2> dummyServiceMock2 = new Mock<IDummyService2>();
            dummyServiceMock2
                .Setup(d => d.Calculate())
                .Returns(1 << 1);

            var policyScopeMock = PolicyScopeMock
                            .SyncPolicy(PolicyNames.SyncPolicyName)
                            .WithServices(dummyServiceMock1.Object, dummyServiceMock2.Object)
                            .WithResultType<int>()
                            .Build();

            Logic logic = new Logic(policyScopeMock.Object);

            // Act
            int result = logic.RunWithResult2Service();

            // Assert
            Assert.Equal((1 << 2) - 1, result);
            Assert.Equal((1 << 2) - 1, logic.LatestResult);
            policyScopeMock.VerifyRunOnce();
        }

        [Fact]
        public void TestRunWithResult3Service()
        {
            // Arrange
            Mock<IDummyService1> dummyServiceMock1 = new Mock<IDummyService1>();
            dummyServiceMock1
                .Setup(d => d.Calculate())
                .Returns(1 << 0);

            Mock<IDummyService2> dummyServiceMock2 = new Mock<IDummyService2>();
            dummyServiceMock2
                .Setup(d => d.Calculate())
                .Returns(1 << 1);

            Mock<IDummyService3> dummyServiceMock3 = new Mock<IDummyService3>();
            dummyServiceMock3
                .Setup(d => d.Calculate())
                .Returns(1 << 2);

            var policyScopeMock = PolicyScopeMock
                            .SyncPolicy(PolicyNames.SyncPolicyName)
                            .WithServices(dummyServiceMock1.Object, dummyServiceMock2.Object, dummyServiceMock3.Object)
                            .WithResultType<int>()
                            .Build();

            Logic logic = new Logic(policyScopeMock.Object);

            // Act
            int result = logic.RunWithResult3Service();

            // Assert
            Assert.Equal((1 << 3) - 1, result);
            Assert.Equal((1 << 3) - 1, logic.LatestResult);
            policyScopeMock.VerifyRunOnce();
        }

        [Fact]
        public void TestRunWithResult4Service()
        {
            // Arrange
            Mock<IDummyService1> dummyServiceMock1 = new Mock<IDummyService1>();
            dummyServiceMock1
                .Setup(d => d.Calculate())
                .Returns(1 << 0);

            Mock<IDummyService2> dummyServiceMock2 = new Mock<IDummyService2>();
            dummyServiceMock2
                .Setup(d => d.Calculate())
                .Returns(1 << 1);

            Mock<IDummyService3> dummyServiceMock3 = new Mock<IDummyService3>();
            dummyServiceMock3
                .Setup(d => d.Calculate())
                .Returns(1 << 2);

            Mock<IDummyService4> dummyServiceMock4 = new Mock<IDummyService4>();
            dummyServiceMock4
                .Setup(d => d.Calculate())
                .Returns(1 << 3);

            var policyScopeMock = PolicyScopeMock
                            .SyncPolicy(PolicyNames.SyncPolicyName)
                            .WithServices(dummyServiceMock1.Object, dummyServiceMock2.Object, dummyServiceMock3.Object, dummyServiceMock4.Object)
                            .WithResultType<int>()
                            .Build();

            Logic logic = new Logic(policyScopeMock.Object);

            // Act
            int result = logic.RunWithResult4Service();

            // Assert
            Assert.Equal((1 << 4) - 1, result);
            Assert.Equal((1 << 4) - 1, logic.LatestResult);
            policyScopeMock.VerifyRunOnce();
        }
    }
}
