// This file has been autogenerated via
// Pekspro.PolicyScope.CodeGenerator.Mock.PolicyScopeResultSelectorMockBuilderGenerator

namespace Pekspro.PolicyScope.Mock
{
    public class AsyncNoServicePolicyScopeResultSelectorMockBuilder
    {
        public AsyncNoServicePolicyScopeResultSelectorMockBuilder(PolicyScopeMockBuilder policyScopeMockBuilder)
        {
            PolicyScopeMockBuilder = policyScopeMockBuilder;
        }

        protected PolicyScopeMockBuilder PolicyScopeMockBuilder { get; }

        public PolicyScopeMockBuilder WithNoResult()
        {
            return PolicyScopeMockBuilder;
        }

        public PolicyScopeMockBuilder WithResultType<TResult>()
        {
            PolicyScopeMockBuilder.NextConfiguration.ReturnType = typeof(TResult);

            return PolicyScopeMockBuilder;
        }
    }

    public class AsyncServicePolicyScopeResultSelectorMockBuilder<T>
    {
        public AsyncServicePolicyScopeResultSelectorMockBuilder(PolicyScopeMockBuilder policyScopeMockBuilder)
        {
            PolicyScopeMockBuilder = policyScopeMockBuilder;
        }

        protected PolicyScopeMockBuilder PolicyScopeMockBuilder { get; }

        public PolicyScopeMockBuilder WithNoResult()
        {
            return PolicyScopeMockBuilder;
        }

        public PolicyScopeMockBuilder WithResultType<TResult>()
        {
            PolicyScopeMockBuilder.NextConfiguration.ReturnType = typeof(TResult);

            return PolicyScopeMockBuilder;
        }
    }

    public class AsyncServicePolicyScopeResultSelectorMockBuilder<T1, T2>
    {
        public AsyncServicePolicyScopeResultSelectorMockBuilder(PolicyScopeMockBuilder policyScopeMockBuilder)
        {
            PolicyScopeMockBuilder = policyScopeMockBuilder;
        }

        protected PolicyScopeMockBuilder PolicyScopeMockBuilder { get; }

        public PolicyScopeMockBuilder WithNoResult()
        {
            return PolicyScopeMockBuilder;
        }

        public PolicyScopeMockBuilder WithResultType<TResult>()
        {
            PolicyScopeMockBuilder.NextConfiguration.ReturnType = typeof(TResult);

            return PolicyScopeMockBuilder;
        }
    }

    public class AsyncServicePolicyScopeResultSelectorMockBuilder<T1, T2, T3>
    {
        public AsyncServicePolicyScopeResultSelectorMockBuilder(PolicyScopeMockBuilder policyScopeMockBuilder)
        {
            PolicyScopeMockBuilder = policyScopeMockBuilder;
        }

        protected PolicyScopeMockBuilder PolicyScopeMockBuilder { get; }

        public PolicyScopeMockBuilder WithNoResult()
        {
            return PolicyScopeMockBuilder;
        }

        public PolicyScopeMockBuilder WithResultType<TResult>()
        {
            PolicyScopeMockBuilder.NextConfiguration.ReturnType = typeof(TResult);

            return PolicyScopeMockBuilder;
        }
    }

    public class AsyncServicePolicyScopeResultSelectorMockBuilder<T1, T2, T3, T4>
    {
        public AsyncServicePolicyScopeResultSelectorMockBuilder(PolicyScopeMockBuilder policyScopeMockBuilder)
        {
            PolicyScopeMockBuilder = policyScopeMockBuilder;
        }

        protected PolicyScopeMockBuilder PolicyScopeMockBuilder { get; }

        public PolicyScopeMockBuilder WithNoResult()
        {
            return PolicyScopeMockBuilder;
        }

        public PolicyScopeMockBuilder WithResultType<TResult>()
        {
            PolicyScopeMockBuilder.NextConfiguration.ReturnType = typeof(TResult);

            return PolicyScopeMockBuilder;
        }
    }

    public class SyncNoServicePolicyScopeResultSelectorMockBuilder
    {
        public SyncNoServicePolicyScopeResultSelectorMockBuilder(PolicyScopeMockBuilder policyScopeMockBuilder)
        {
            PolicyScopeMockBuilder = policyScopeMockBuilder;
        }

        protected PolicyScopeMockBuilder PolicyScopeMockBuilder { get; }

        public PolicyScopeMockBuilder WithNoResult()
        {
            return PolicyScopeMockBuilder;
        }

        public PolicyScopeMockBuilder WithResultType<TResult>()
        {
            PolicyScopeMockBuilder.NextConfiguration.ReturnType = typeof(TResult);

            return PolicyScopeMockBuilder;
        }
    }

    public class SyncServicePolicyScopeResultSelectorMockBuilder<T>
    {
        public SyncServicePolicyScopeResultSelectorMockBuilder(PolicyScopeMockBuilder policyScopeMockBuilder)
        {
            PolicyScopeMockBuilder = policyScopeMockBuilder;
        }

        protected PolicyScopeMockBuilder PolicyScopeMockBuilder { get; }

        public PolicyScopeMockBuilder WithNoResult()
        {
            return PolicyScopeMockBuilder;
        }

        public PolicyScopeMockBuilder WithResultType<TResult>()
        {
            PolicyScopeMockBuilder.NextConfiguration.ReturnType = typeof(TResult);

            return PolicyScopeMockBuilder;
        }
    }

    public class SyncServicePolicyScopeResultSelectorMockBuilder<T1, T2>
    {
        public SyncServicePolicyScopeResultSelectorMockBuilder(PolicyScopeMockBuilder policyScopeMockBuilder)
        {
            PolicyScopeMockBuilder = policyScopeMockBuilder;
        }

        protected PolicyScopeMockBuilder PolicyScopeMockBuilder { get; }

        public PolicyScopeMockBuilder WithNoResult()
        {
            return PolicyScopeMockBuilder;
        }

        public PolicyScopeMockBuilder WithResultType<TResult>()
        {
            PolicyScopeMockBuilder.NextConfiguration.ReturnType = typeof(TResult);

            return PolicyScopeMockBuilder;
        }
    }

    public class SyncServicePolicyScopeResultSelectorMockBuilder<T1, T2, T3>
    {
        public SyncServicePolicyScopeResultSelectorMockBuilder(PolicyScopeMockBuilder policyScopeMockBuilder)
        {
            PolicyScopeMockBuilder = policyScopeMockBuilder;
        }

        protected PolicyScopeMockBuilder PolicyScopeMockBuilder { get; }

        public PolicyScopeMockBuilder WithNoResult()
        {
            return PolicyScopeMockBuilder;
        }

        public PolicyScopeMockBuilder WithResultType<TResult>()
        {
            PolicyScopeMockBuilder.NextConfiguration.ReturnType = typeof(TResult);

            return PolicyScopeMockBuilder;
        }
    }

    public class SyncServicePolicyScopeResultSelectorMockBuilder<T1, T2, T3, T4>
    {
        public SyncServicePolicyScopeResultSelectorMockBuilder(PolicyScopeMockBuilder policyScopeMockBuilder)
        {
            PolicyScopeMockBuilder = policyScopeMockBuilder;
        }

        protected PolicyScopeMockBuilder PolicyScopeMockBuilder { get; }

        public PolicyScopeMockBuilder WithNoResult()
        {
            return PolicyScopeMockBuilder;
        }

        public PolicyScopeMockBuilder WithResultType<TResult>()
        {
            PolicyScopeMockBuilder.NextConfiguration.ReturnType = typeof(TResult);

            return PolicyScopeMockBuilder;
        }
    }

}
