name: Build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.302

    - name: Restore dependencies
      run: dotnet restore ./src/

    - name: Build
      run: dotnet build ./src/ --no-restore --configuration DebugLocalReferences

    - name: Test
      run: dotnet test ./src/ --no-build  --configuration DebugLocalReferences --verbosity normal

    - name: Change directory
      run: cd ./src/

    - name: Test
      run: dotnet run --configuration DebugLocalReferences dotnet run --project .\PolicyScope\Pekspro.PolicyScope.CodeGenerator\Pekspro.PolicyScope.CodeGenerator.csproj

  test-linux:
    runs-on: windows-latest
    if: false == true

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.302

    - name: Restore dependencies
      run: dotnet restore ./src/

    - name: Build
      run: dotnet build ./src/ --no-restore --configuration DebugLocalReferences

    - name: Test
      run: dotnet test ./src/ --no-build  --configuration DebugLocalReferences --verbosity normal
