name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.302

    - name: Restore dependencies
      run: dotnet restore ./src/

    - name: Build
      run: dotnet build ./src/ --no-restore

    - name: Test
      run: dotnet test ./src/ --no-build --verbosity normal

    - name: Pack PolicyScope
      run: dotnet pack ./src/PolicyScope/Pekspro.PolicyScope/Pekspro.PolicyScope.csproj --verbosity normal

    - name: Pack PolicyScope.Mock
      run: dotnet pack ./src/PolicyScope/Pekspro.PolicyScope.Mock/Pekspro.PolicyScope.Mock.csproj --verbosity normal
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: NuGet-packages
        path: |
          ./**/*.nupkg
          ./**/*.snupkg

