name: Build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Restore dependencies
      run: dotnet restore ./src/

    - name: Build
      run: dotnet build ./src/ --no-restore --configuration DebugLocalReferences

    - name: Test
      run: dotnet test ./src/ --no-build  --configuration DebugLocalReferences --verbosity normal

    - name: Verify code generator
      run: dotnet run --configuration DebugLocalReferences dotnet run --configuration DebugLocalReferences --project ./src/PolicyScope/Pekspro.PolicyScope.CodeGenerator/Pekspro.PolicyScope.CodeGenerator.csproj ./src/

  test-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Restore dependencies
      run: dotnet restore ./src/

    - name: Build
      run: dotnet build ./src/ --no-restore --configuration DebugLocalReferences

    - name: Test
      run: dotnet test ./src/ --no-build --configuration DebugLocalReferences --verbosity normal

    - name: Verify code generator
      run: dotnet run --configuration DebugLocalReferences dotnet run --configuration DebugLocalReferences --project ./src/PolicyScope/Pekspro.PolicyScope.CodeGenerator/Pekspro.PolicyScope.CodeGenerator.csproj ./src/
