# This is a basic workflow that is manually triggered

name: Deploy Main

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      pushToNuget:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Push to NuGet'
        # Default value if no value is explicitly provided
        default: '0'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.pushToNuget }}"
    - name: Not pushing
      if: github.event.inputs.pushToNuget != '1'
      run: echo "Will not push to NuGet"
    - name: Pushing
      if: github.event.inputs.pushToNuget == '1'
      run: echo "Will push to NuGet"'
  
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.302

    - name: Restore dependencies
      run: dotnet restore ./src/PolicyScope/Pekspro.PolicyScope/Pekspro.PolicyScope.csproj

    - name: Build
      run: dotnet build ./src/PolicyScope/Pekspro.PolicyScope/Pekspro.PolicyScope.csproj --no-restore --configuration Release

    - name: Pack PolicyScope
      run: dotnet pack ./src/PolicyScope/Pekspro.PolicyScope/Pekspro.PolicyScope.csproj --verbosity normal --configuration Release --include-symbols -p:GITHUB_ACTIONS=true
          
    - name: Upload artifacts
      if: github.event.inputs.pushToNuget == '1'
      uses: actions/upload-artifact@v2
      with:
        name: NuGet-packages
        path: |
          ./**/*.nupkg
          ./**/*.snupkg
  
  publish:
    needs: [build]
    if: github.event.inputs.pushToNuget == '1' 
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Pushing 2      
      run: echo "Will push to NuGet 2"
  
    - name: Upload artifacts
      if: github.event.inputs.pushToNuget == '1'
      uses: actions/upload-artifact@v2
      with:
        name: NuGet-packages
        path: |
          ./**/*.nupkg
          ./**/*.snupkg
